### PR TITLE
Support for Teensy 4

### PR DESCRIPTION
**Pull request by pedvide**
From issue #41.

Adds support for Teensy 4.
It minimizes the lines of code that deal directly with registers.
It packs all the registers into a struct, and each ADC gets its base address.
Most configuration #defines and enums are in a separate file now (will improve in the future)
ADC and ADC_Module interfaces define methods for the capabilities of each board, to save space.

TODO:
 - [x] Test synchronized measurements.
 - [x] Improve atomic code for T4.
         It seems the T4 ADC registers do not have any type of atomic access (bitband, BME, or SCT)
 - [x] Check that the clock, conversion and sampling speeds are appropriate.
 - [x] Make interrupts work

### CODE REVIEW

**Comment by mjs513** [comment]
Good morning @pedvide 
Downloaded your "teensy4" branch and ran the adc_test.ino sketch.  Nice test by the way but all the COMPARISON tests failed.  Which is a little miss leading in I attach A0 to 3.3v I will get:
```
Comparison didn't succeed.
Comparison
-70000
COMPARE TEST FAIL
COMPARE RANGE TEST PASS
```
 Another run with a it to low:
```
Comparison didn't fail.

COMPARE TEST FAIL
COMPARE RANGE TEST PASS
```
For the compare stuff I had added a TIMEOUT ERROR which seems to occur.  Going to play and see if that's it and let you know.

Second thing Pullup/pulldown tests failed.

I did get ALL COMBINATIONS TEST PASS but the note on the side stated PULLDOWN FAILED.

**Comment by mjs513** [comment]
Ok - retested with my compare test sketch - seems to be working:
```
#if !defined(__IMXRT1062__)  // Teensy 4.x
#error "Only runs on T4"
#endif
#include <ADC.h>

ADC *adc = new ADC(); // adc object

uint8_t pin_cmp = 15;
int8_t resolution = 12;

void setup() {
  // put your setup code here, to run once:
  while (!Serial && millis() < 5000) ;
  Serial.begin(115200);
  Serial.println("Quick and dirty T4 Analog compare stuff");

  
  adc->setResolution(resolution, 0);
  //since cmp pins are on adc4 we have to change the resoultion
  // measurement will be ready if value < 1.0V
  //adc->enableCompare(2100, 1, ADC_0); 
  
  // ready if value lies out of [1.0,2.0] V
  adc->enableCompareRange(1500, 3000, 0, 0, ADC_0); 
}

void loop() {
  // put your main code here, to run repeatedly:
  int value;
  //value = adc->analogRead(15);
  //value = adc->analogRead(pin_cmp, 0, 0);
  adc->startSingleRead(pin_cmp, 0);
  while (adc->isConverting(0) ) ;
  value = adc->readSingle(0);

  //if(adc->adc0->fail_flag == ADC_ERROR::TIMEOUT) {
    //Serial.println("Some other error happened when comparison should have succeeded.");
    //adc->adc0->printError();
  //} else {
    Serial.println(value);
  //}
  adc->adc0->resetError();

  delay(50);
}
```

**Comment by pedvide** [comment]
> 
> 
> Good morning @pedvide
> Downloaded your "teensy4" branch and ran the adc_test.ino sketch. Nice test by the way but all the COMPARISON tests failed. Which is a little miss leading in I attach A0 to 3.3v I will get:
> 
> ```
> Comparison didn't succeed.
> Comparison
> -70000
> COMPARE TEST FAIL
> ```
> 
> Another run with a it to low:
> 
> ```
> Comparison didn't fail.
> 
> COMPARE TEST FAIL
> COMPARE RANGE TEST PASS
> ```
> 
> For the compare stuff I had added a TIMEOUT ERROR which seems to occur. Going to play and see if that's it and let you know.

Hey, that test should be run with the board not connected to anything. It uses the internal pullup and pulldown resistors. The comparison test sets a 1 V threshold, so with a pullup it should fail and with the pulldown it should succeed. By connecting it to VDD or GND one of the tests will always fail.
Can you try running it with nothing connected?

> 
> Second thing Pullup/pulldown tests failed.
> 
> I did get ALL COMBINATIONS TEST PASS but the note on the side stated PULLDOWN FAILED.

The combination test is a bit different. There are expected failures when the conversion and sampling speeds are too high so that the measured voltage is different from GND (that tests uses only pulldowns). For Teensy 4 it seems that most clock, sampling and conversion speeds run too fast for a good sample, so you see many errors. Other boards have failures too.

Thanks for testing it!

**Comment by pedvide** [comment]
> For the compare stuff I had added a TIMEOUT ERROR which seems to occur. Going to play and see if that's it and let you know.

In your (and KurtE) code you try to detect when a conversion has finished by checking the COCO flag, but that is not right. The conversion is done when ADACT (in the SC2 or GC registers) is cleared. If COCO is set then the comparison (if any) succeeded, if COCO is clear then the comparison failed. You don't need to have a timeout, the ADC will always finish a conversion.

**Comment by mjs513** [comment]
> Hey @mjs513, that test should be run with the board not connected to anything. It uses the internal pullup and pulldown resistors. The comparison test sets a 1 V threshold, so with a pullup it should fail and with the pulldown it should succeed. By connecting it to VDD or GND one of the tests will always fail.
> Can you try running it with nothing connected?

Sorry - never played with ADC lib so learning as I go anyway.  Reran the test with nothing attached and all tests passed except for HIGH SPEED Combo tests (failed on PULL_DOWN:
```
PULLUP TEST PASS
PULLDOWN TEST PASS
COMPARE TEST PASS
COMPARE RANGE TEST PASS
AVERAGES TEST PASS

Average: 4, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 4, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 4, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 8, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: LOW_MED_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 16, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: LOW_MED_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 8, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: LOW_MED_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 10, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: MED_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: MED_HIGH_SPEED. PULLDOWN FAILED.
Average: 32, Resolution: 12, Conversion speed: HIGH_SPEED, Sampling speed: HIGH_SPEED. PULLDOWN FAILED.
ALL COMBINATIONS TEST PASS
ALL TEST PASSED.
```

> In your (and KurtE) code you try to detect when a conversion has finished by checking the COCO flag, but that is not right. The conversion is done when ADACT (in the SC2 or GC registers) is cleared. If COCO is set then the comparison (if any) succeeded, if COCO is clear then the comparison failed. You don't need to have a timeout, the ADC will always finish a conversion.

Thanks for the info didn't realize that.

**Comment by pedvide** [comment]
@mjs513, don't apologize! The examples lack instructions, I should work on that too!

**Pull request merged**
