### PR TITLE
 Use VREF in external file

### PR DESCRIPTION
**Pull request by pedvide**
add VREF file
separate VREF code into VREF.h
use static interal_vref variable in ADC_Module

### CODE REVIEW

**Comment by pedvide** [comment]
Sorry for the silly commits reverting things....

**Comment by crteensy** [comment]
now you have the internal reference in a separate class, non-static. Sematically that means that there could be more than one. OTOH, if you make the methods static, you have a class with only public, static methods. Wouldn't that be overkill? You could also put them into a namespace instead.
 *IF* (and that's a bit if) the upcoming totally overpowered next teensy has several internal references to care about, you can still change vref to be a "normal" class.

**Comment by pedvide** [comment]
Yes, I agree. I've changed it to a namespace. what do you think?

**Comment by crteensy** [comment]
Looks reasonable. I'll contribute an example of you don't mind

**Comment by pedvide** [comment]
Please do!

**Comment by crteensy** [comment]
When trying to compile an example I got "multiple definition" errors. Am I doing something wrong? 
Sketch:

#include <ADC.h>
#include <VREF.h>

ADC* adc;

void setup() {
  Serial.begin(9600);
  adc = new ADC();
  VREF::start(VREF_SC_MODE_LV_HIGHPOWERBUF);
  VREF::waitUntilStable();
}

void loop() {
  int value = adc->analogRead(ADC_INTERNAL_SOURCE::VREF_OUT, ADC_1);
  if (value == ADC_ERROR_VALUE)
  {
    Serial.println("error");
  }
  float voltage = 1.2/value*(adc->getMaxValue(ADC_1));
  Serial.print("value = ");Serial.print(value);
  Serial.print(" ^= ");Serial.println(voltage);
  delay(1000);
}

**Comment by crteensy** [comment]
inline attributes to start() and waitUntilStable() must be added to make the multiple definition errors disappear (makes sense!). Example sketch also shows expected output then.

**Comment by pedvide** [comment]
Yes, you're right. I'll fix that and add your example. You can also do that yourself if you want to!

**Comment by pedvide** [comment]
Sorry crteensy, I ended up working on this and I didn't see your commit. Have a look at my example, it automatically finds the optimum trim value.

**Pull request merged**
